apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qe70fnn06-go
  janus-idp.io/tekton: qe70fnn06-go
  backstage.io/kubernetes-id: qe70fnn06-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qe70fnn06-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
