apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qe70fnn06-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qe70fnn06-go 
  name: qe70fnn06-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qe70fnn06-go 
